-- MySQL Script generated by Dennis
-- Tue Mar 13 12:14:25 2018
-- Model: New Model  

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE = 'TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema WorkoutPlan
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `WorkoutPlan`;

-- -----------------------------------------------------
-- Schema WorkoutPlan
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `WorkoutPlan`
  DEFAULT CHARACTER SET utf8;
USE `WorkoutPlan`;

-- -----------------------------------------------------
-- Table `WorkoutPlan`.`WorkoutPlanRow`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WorkoutPlan`.`WorkoutPlanRow`;

CREATE TABLE IF NOT EXISTS `WorkoutPlan`.`WorkoutPlanRow` (
  `id`          INT          NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NULL,
  `duration`    TIME         NOT NULL,
  `intensity`   VARCHAR(255) NOT NULL,
  `comment`     VARCHAR(255) NULL,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `WorkoutPlan`.`WorkoutPlan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WorkoutPlan`.`WorkoutPlan`;

CREATE TABLE IF NOT EXISTS `WorkoutPlan`.`WorkoutPlan` (
  `id`                INT          NOT NULL AUTO_INCREMENT,
  `createdForUser`    VARCHAR(255) NOT NULL,
  `parentPlan`        VARCHAR(255) NULL,
  `WorkoutPlanRow_id` INT          NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_WorkoutPlan_WorkoutPlanRow_idx` (`WorkoutPlanRow_id` ASC),
  CONSTRAINT `fk_WorkoutPlan_WorkoutPlanRow`
  FOREIGN KEY (`WorkoutPlanRow_id`)
  REFERENCES `WorkoutPlan`.`WorkoutPlanRow` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
)
  ENGINE = InnoDB;

