-- MySQL Script generated by MySQL Workbench
-- Sat Feb 24 14:22:21 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ecosystem
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ecosystem` ;

-- -----------------------------------------------------
-- Schema ecosystem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecosystem` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `ecosystem` ;

-- -----------------------------------------------------
-- Table `UserAccount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UserAccount` (
  `id` INT NOT NULL,
  `firstname` VARCHAR(255) NOT NULL,
  `lastname` VARCHAR(255) NOT NULL,
  `height` FLOAT(5,2) NOT NULL COMMENT 'given in centimeters, allows decimals',
  `birthdate` DATE NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL COMMENT 'needs to be cryptated',
  `email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'Shall be a useraccount which allows you to get access to personal info and give info to service provider which processes info and forwards it to trainer, which again produces a workout plan to the useraccount';


-- -----------------------------------------------------
-- Table `Weight`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Weight` (
  `id` INT NOT NULL,
  `currentweight` VARCHAR(255) NOT NULL,
  `date` DATE NOT NULL,
  `UserAccount_id` INT NOT NULL,
  PRIMARY KEY (`id`, `UserAccount_id`),
  INDEX `fk_Weight_UserAccount_idx` (`UserAccount_id` ASC),
  CONSTRAINT `fk_Weight_UserAccount`
    FOREIGN KEY (`UserAccount_id`)
    REFERENCES `UserAccount` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RestingHeartRate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RestingHeartRate` (
  `id` INT NOT NULL,
  `date` DATE NOT NULL,
  `heartrate` INT NOT NULL,
  `UserAccount_id` INT NOT NULL,
  PRIMARY KEY (`id`, `UserAccount_id`),
  INDEX `fk_RestingPulse_UserAccount1_idx` (`UserAccount_id` ASC),
  CONSTRAINT `fk_RestingPulse_UserAccount1`
    FOREIGN KEY (`UserAccount_id`)
    REFERENCES `UserAccount` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WorkoutSession`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WorkoutSession` (
  `id` INT NOT NULL,
  `time` TIMESTAMP NOT NULL,
  `intensity` INT(10) NOT NULL,
  `KCal` DECIMAL NOT NULL,
  `AvgHeartRate` INT NOT NULL,
  `MaxHeartRate` INT NOT NULL,
  `DistanceRun` INT NOT NULL,
  `UserAccount_id` INT NOT NULL,
  PRIMARY KEY (`id`, `UserAccount_id`),
  INDEX `fk_WorkoutSession_UserAccount1_idx` (`UserAccount_id` ASC),
  CONSTRAINT `fk_WorkoutSession_UserAccount1`
    FOREIGN KEY (`UserAccount_id`)
    REFERENCES `UserAccount` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ServiceProvider`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ServiceProvider` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Goal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Goal` (
  `id` INT NOT NULL,
  `description` TEXT NOT NULL,
  `isCompleted` TINYINT NOT NULL,
  `isCurrent` TINYINT NOT NULL,
  `UserAccount_id` INT NOT NULL,
  PRIMARY KEY (`id`, `UserAccount_id`),
  INDEX `fk_Goal_UserAccount1_idx` (`UserAccount_id` ASC),
  CONSTRAINT `fk_Goal_UserAccount1`
    FOREIGN KEY (`UserAccount_id`)
    REFERENCES `UserAccount` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ImprovifyTrainer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ImprovifyTrainer` (
  `id` INT NOT NULL,
  `Name` VARCHAR(255) NOT NULL,
  `Goal_id` INT NOT NULL,
  `Goal_UserAccount_id` INT NOT NULL,
  `UserAccount_id` INT NOT NULL,
  PRIMARY KEY (`id`, `UserAccount_id`),
  INDEX `fk_ImprovifyTrainer_Goal1_idx` (`Goal_id` ASC, `Goal_UserAccount_id` ASC),
  INDEX `fk_ImprovifyTrainer_UserAccount1_idx` (`UserAccount_id` ASC),
  CONSTRAINT `fk_ImprovifyTrainer_Goal1`
    FOREIGN KEY (`Goal_id` , `Goal_UserAccount_id`)
    REFERENCES `Goal` (`id` , `UserAccount_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ImprovifyTrainer_UserAccount1`
    FOREIGN KEY (`UserAccount_id`)
    REFERENCES `UserAccount` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WorkoutPlan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WorkoutPlan` (
  `id` INT NOT NULL,
  `DurationPeriod` INT NOT NULL,
  `ImprovifyTrainer_id` INT NOT NULL,
  `WorkoutSession_id` INT NOT NULL,
  `WorkoutSession_UserAccount_id` INT NOT NULL,
  `UserAccount_id` INT NOT NULL,
  PRIMARY KEY (`id`, `ImprovifyTrainer_id`, `UserAccount_id`),
  INDEX `fk_WorkoutPlan_ImprovifyTrainer1_idx` (`ImprovifyTrainer_id` ASC),
  INDEX `fk_WorkoutPlan_WorkoutSession1_idx` (`WorkoutSession_id` ASC, `WorkoutSession_UserAccount_id` ASC),
  INDEX `fk_WorkoutPlan_UserAccount1_idx` (`UserAccount_id` ASC),
  CONSTRAINT `fk_WorkoutPlan_ImprovifyTrainer1`
    FOREIGN KEY (`ImprovifyTrainer_id`)
    REFERENCES `ImprovifyTrainer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_WorkoutPlan_WorkoutSession1`
    FOREIGN KEY (`WorkoutSession_id` , `WorkoutSession_UserAccount_id`)
    REFERENCES `WorkoutSession` (`id` , `UserAccount_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_WorkoutPlan_UserAccount1`
    FOREIGN KEY (`UserAccount_id`)
    REFERENCES `UserAccount` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PeriodPlan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PeriodPlan` (
  `id` INT NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT NOW(),
  `periodStart` DATETIME NOT NULL,
  `periodEnd` DATETIME NOT NULL,
  `WorkoutPlan_id` INT NOT NULL,
  `ImprovifyTrainer_id` INT NULL,
  `UserAccount_id` INT NOT NULL,
  PRIMARY KEY (`id`, `UserAccount_id`),
  INDEX `fk_PeriodPlan_WorkoutPlan1_idx` (`WorkoutPlan_id` ASC),
  INDEX `fk_PeriodPlan_ImprovifyTrainer1_idx` (`ImprovifyTrainer_id` ASC),
  INDEX `fk_PeriodPlan_UserAccount1_idx` (`UserAccount_id` ASC),
  CONSTRAINT `fk_PeriodPlan_WorkoutPlan1`
    FOREIGN KEY (`WorkoutPlan_id`)
    REFERENCES `WorkoutPlan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PeriodPlan_ImprovifyTrainer1`
    FOREIGN KEY (`ImprovifyTrainer_id`)
    REFERENCES `ImprovifyTrainer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PeriodPlan_UserAccount1`
    FOREIGN KEY (`UserAccount_id`)
    REFERENCES `UserAccount` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
