POST http://localhost:2222/goal
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: Basic dGVzdDoxMjM=

{
  "description": "Run faster than Bendik",
  "isCompleted": false,
  "isCurrent": true,
  "user": {
    "id": 1
  }
}

###
