POST http://localhost:2222/user
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "firstName": "Test",
  "lastName": "User",
  "height": 1.85,
  "birthDate": "2015-03-04",
  "username": "test",
  "password": "123",
  "email": "krirek@stud.ntnu.no"
}

###
