POST http://localhost:2222/restingheartrate
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: Basic dGVzdDoxMjM=

{
  "measuredAt": "2017-08-08",
  "heartRate": 123,
  "measuredBy": {
    "id": 1
  }
}

###
